### ISSUE TITLE
ProFTP sftp not working

### ISSUE THREAD

**Issue by KaidenP** [bambusoft/sentora-paranoid#4]
Proftp complains about a 'segmentation fault` when the following lines are uncommented

``` xml
#<IfModule mod_sftp.c>
#  <VirtualHost %%LOCAL_IP%%>
#               TLSRequired off
#               ServerName "<fqdn> sFTP Server"
#               SFTPEngine on
#               Port 115
#               SFTPLog /var/sentora/logs/proftpd/sftp.log
#
#               # Configure both the RSA and DSA host keys, using the same host key
#               # files that OpenSSH uses.
#               SFTPHostKey /etc/ssh/ssh_host_rsa_key
#               SFTPHostKey /etc/ssh/ssh_host_dsa_key
#
#               #SFTPAuthMethods publickey
#               #SFTPAuthorizedUserKeys file:/etc/sentora/configs/proftpd/authorized_keys/%u
#               SFTPAuthMethods password
#               # Enable compression
#               SFTPCompression delayed
#  </VirtualHost>
#</IfModule>
```

After the comment everything works fine.

**Comment by bambusoft** [comment]
It looks like  %%LOCAL_IP%% were  not changed to the actual IP, did you ran the script twice?, ignoring the warnings..., can you post the sentora and sentora-paranoid log files?

**Comment by KaidenP** [comment]
This time It was only run once. I do have two ips on my server however, so that might of caused a problem.

Is this SSH FTP or Simple FTP?

**Comment by bambusoft** [comment]
The script try to setup both FTP and sFTP, the problem you described in the configuration is for sFTP module

**Comment by KaidenP** [comment]
What I meant is is it for SFTP (SSH File Transfer Protocol) or SFTP (Simple File Transfer Protocol)?

**Comment by bambusoft** [comment]
SSH File Transfer Protocol

**Comment by bambusoft** [comment]
I changed the script to take the first ip in the local_ip variable, but my tests shows me that in case of more than one ip, local_ip is taking both ips and the ftp config file must have both ips and not the replacement tag, so I think there must be another condition causing this.
(Also I added a validate replacement function to inform user about replacements strings not changed for some reason)

**Comment by KaidenP** [comment]
A possible idea would be to test if there is multiple IPs, and then ask the user if they want to enable It.

Or, have it create a VirtualHost for each IP detected, although I do not know if that will work. I will not pretend to be a proFTP guru.

Honestly, in my case at least, I will never use the SFTP used in proFTP. FTPS is good enough for me. I wouldn't have even known it was possible if I didn't have a problem with it. I only use SFTP when doing remote administration, with large files.

**Comment by bambusoft** [comment]
Sounds like a good idea, detect how many ips and ask which ones to configure, let me dig into proFTPd documentation and put in the next version things to do. Thank you

**Comment by bambusoft** [comment]
In my case, I have two different clients that want to transfer sensible data via secure ftp channel

**Comment by KaidenP** [comment]
Is ftps not secure?

**Comment by bambusoft** [comment]
Yes it is, but the mod_sftp module implements the SSH2 protocol and its own SFTP subsystem for secure file transfers over an SSH2 connection.... and SFTP is much easier to port through firewalls
(In my case it was a client requierement and not by ftps itself)
