### ISSUE TITLE
Can't receive Mails from Outside after install of Paranoid

### ISSUE THREAD

**Issue by billfoo** [bambusoft/sentora-paranoid#8]
Hello,

everything works fine but i have this error if i want to send mails to the paranoid mail server:

An error occurred while sending mail. The mail server responded:  
4.1.1 info@mail.com: Recipient address rejected: User unknown in virtual mailbox table.
 Please check the message recipient "info@mail.com" and try again.

...

local send mails works but not from outside.

**Comment by bambusoft** [comment]
Hi:
did you install sentora_paranoid right after sentora installation?
Is the info@mail.com an alias or forward to annother account?
does info@mail.com appears into the sentora_postfix mailbox table and into the sentora_core x_mailbox table?

**Comment by billfoo** [comment]
hello,
yes right after sentora installation,
its a mailbox, not alias and not forward...

i checked sentora_postfix in mysql.. mailbox is listed, sentora_core x_mailbox too

maybe something with the hostname?... because i m running vps and i can not edit the hostname... it will be overwritten every time after reboot..

the problem is only if i want to receive mails from outside.. maybe something with the firewall (fail2ban) or other restrictions?

**Comment by bambusoft** [comment]
Reading the log entry, info@mail.com does not exist in virtual mailbox, postfix can't find info as mailbox or alias in the domain mail.com, some reasons could be:

a) Domain name is resolving MX record to a different server IP wich is answering you with the error message
b) User does not exist in the virtual table (postfix configuration)
c) Email client configuration has mispelled domain name

did you see any error into the sentora-paranoid server mail log?

**Comment by billfoo** [comment]
so i m closer to the problem now...
now i can send from every mail but not from a mail with a self signed certificate (sentora without paranoid).. maybe its that the problem?

**Comment by bambusoft** [comment]
sentora 1.0.x does not enable TLS in postfix by default, you need to enable it if you want to use secure connections; sentora-paranoid script change sentora's postfix configuration to enable it, but I recommend you: to do many tests as you require with sentora alone, and when you feel confortable reinstall sentora+sentora-paranoid and do many tests again.

I´m closing this issue by now. If you need further assitance please open a new issue
